<a href="https://colab.research.google.com/github/prajjaldhar/Numpy_DataSc/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
print("prajjal")

prajjal


#Creating Numpy Arrays

In [30]:
import numpy as np

one dimensional array

In [31]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [32]:
b = np.array([2,1,4,3])
print(b)

[2 1 4 3]


In [33]:
c = np.array([5,1,2,3,7,89,45])
print(c)

[ 5  1  2  3  7 89 45]


Two dimensional array

In [34]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
b1 = np.array([[1,72,30],[40,50,60],[7,8,9]])
print(b1)

[[ 1 72 30]
 [40 50 60]
 [ 7  8  9]]


In [36]:
c1 = np.array([[1,72,30],[40,50,60],[7,8,9]])
print(c1)

[[ 1 72 30]
 [40 50 60]
 [ 7  8  9]]


variations in 2d array

In [37]:
d1 = np.array([[1,72,30],[40,50,45]])
print(d1)

[[ 1 72 30]
 [40 50 45]]


In [38]:
e1 = np.array([[1],[40],[7]])
print(e1)

[[ 1]
 [40]
 [ 7]]


In [39]:
f1 = np.array([[1,2],[40,2],[7,2]])
print(f1)

[[ 1  2]
 [40  2]
 [ 7  2]]


data type

In [40]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

1d array example

In [41]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2d array

In [47]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.random.random((3,4))

array([[0.52695695, 0.97478894, 0.42682302, 0.13179394],
       [0.70017911, 0.0367055 , 0.47200749, 0.04046223],
       [0.88977514, 0.30491183, 0.16063034, 0.19343059]])

In [61]:
np.random.randint(10,size=(5,4))

array([[4, 7, 4, 3],
       [4, 7, 6, 9],
       [9, 8, 1, 5],
       [3, 9, 6, 9],
       [7, 7, 1, 4]])

In [62]:
a3 = np.array([1,2,3])

In [65]:
a3.ndim

1

In [67]:
print(a3.shape)
a3

(3,)


array([1, 2, 3])

In [71]:
b3 = np.array([[1,2,3],[4,5,6],[7,8,87]])
print(b3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 87]]


In [70]:
b3.ndim

2

In [72]:
b3.shape

(3, 3)

In [76]:
x3 = np.array([[[1,2,3],[4,5,6],[7,8,87]],[[2,8,3],[4,5,6],[7,8,87]]])

In [77]:
print(x3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8 87]]

 [[ 2  8  3]
  [ 4  5  6]
  [ 7  8 87]]]


In [78]:
x3.ndim

3

In [79]:
print(x3.shape)

(2, 3, 3)


In [82]:
x4 = np.array([[[[1,2,3],[4,5,6],[7,8,87]],[[2,8,3],[4,5,6],[7,8,87]]],[[[1,2,3],[4,5,6],[7,8,87]],[[2,8,3],[4,5,6],[7,8,87]]]])

In [83]:
print(x4)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8 87]]

  [[ 2  8  3]
   [ 4  5  6]
   [ 7  8 87]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8 87]]

  [[ 2  8  3]
   [ 4  5  6]
   [ 7  8 87]]]]


In [84]:
x4.ndim

4

In [85]:
x4.shape

(2, 2, 3, 3)

In [89]:
a1= np.array([36,4,16,7,8,9,87,66,24])

In [91]:
a1[2:5]

array([16,  7,  8])

In [93]:
a1[6:]

array([87, 66, 24])

In [94]:
a1[1:]

array([ 4, 16,  7,  8,  9, 87, 66, 24])

In [95]:
a1[::-1]

array([24, 66, 87,  9,  8,  7, 16,  4, 36])

In [99]:
print(a1)
a1[::2]

[36  4 16  7  8  9 87 66 24]


array([36, 16,  8, 87, 24])

In [100]:
print(a1)
a1[::3]

[36  4 16  7  8  9 87 66 24]


array([36,  7, 87])

In [101]:
print(a1)
a1[::-1]

[36  4 16  7  8  9 87 66 24]


array([24, 66, 87,  9,  8,  7, 16,  4, 36])

In [102]:
print(a1)
a1[::-2]

[36  4 16  7  8  9 87 66 24]


array([24, 87,  8, 16, 36])

In [103]:
print(a1)
a1[::-3]

[36  4 16  7  8  9 87 66 24]


array([24,  9, 16])

In [104]:
print(a1)
a1[1:7:2]

[36  4 16  7  8  9 87 66 24]


array([4, 7, 9])

In [106]:
print(a1)
a1[1:7:-1]

[36  4 16  7  8  9 87 66 24]


array([], dtype=int64)

In [107]:
a1[7:1:-1]

array([66, 87,  9,  8,  7, 16])

In [109]:
d1 = np.array([[1,72,30],[40,50,45],[70,5,15]])
print(d1)

[[ 1 72 30]
 [40 50 45]
 [70  5 15]]


In [112]:
d1[0,:]

array([ 1, 72, 30])

In [113]:
d1[:,1]

array([72, 50,  5])

In [114]:
d1[1:,1:]

array([[50, 45],
       [ 5, 15]])

In [117]:
a5 = np.arange(12).reshape(3,4)
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
a5[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [122]:
a5[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [124]:
a5[1:,1::2]

array([[ 5,  7],
       [ 9, 11]])

In [128]:
a5[1:,0::3]

array([[ 4,  7],
       [ 8, 11]])

In [132]:
a5[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [138]:
a5[  0 : 2 :      , 1 :   :    ]

array([[1, 2, 3],
       [5, 6, 7]])

In [139]:
a3 = np.arange(27).reshape(3,3,3)

In [140]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [141]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [142]:
a3[::,::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [143]:
a3[::2,::,::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [145]:
a3[0,1:2,]

array([[3, 4, 5]])

In [146]:
a3[1,:,1:2]

array([[10],
       [13],
       [16]])

In [147]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [148]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [149]:
a3[::2,2,::2]

array([[ 6,  8],
       [24, 26]])