<a href="https://colab.research.google.com/github/prajjaldhar/DataScience/blob/main/uber_datanalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = np.column_stack([
    user_id,
    rider_id,
    total_trips,
    distance,
    experience,
    rating
])

print(data)
n = 25

user_id = np.arange(1,26)

rider_id = np.random.randint(1001,1026, n)

total_trips = np.random.randint(0, 721, n)       # 0 to 720

distance = np.random.randint(15, 12001, n)       # 15 to 12000

experience = np.random.randint(0, 17, n)         # 0 to 17 years

rating = np.random.randint(1, 6, n)              # 1 to 5



[[    1  1019   622  2392    12     2]
 [    2  1014   674  1469    15     1]
 [    3  1020   225 10186    14     4]
 [    4  1012   403  2084    16     5]
 [    5  1016   603   686    14     3]
 [    6  1002   198  5232     7     3]
 [    7  1022   415  5994    16     5]
 [    8  1012   516  7055    15     1]
 [    9  1005   176   904     6     1]
 [   10  1022   367   136     8     3]
 [   11  1001   199 10091    13     1]
 [   12  1002   659   821    10     1]
 [   13  1003   369  5228     8     1]
 [   14  1025   206 11234    11     2]
 [   15  1019    40  8696     5     4]
 [   16  1008   316 10908     4     1]
 [   17  1014     0  2861     7     5]
 [   18  1022   618 11448     9     2]
 [   19  1010   586  9200    15     5]
 [   20  1015   486  1963     4     5]
 [   21  1013   161  6053     2     4]
 [   22  1024    91   186     8     4]
 [   23  1007   480  9463    12     5]
 [   24  1002   568  2142    15     3]
 [   25  1023   239  5664    11     5]]


In [ ]:
result = np.concatenate((user_id, rider_id), axis=0)

print(result)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25 1019 1014 1020
 1012 1016 1002 1022 1012 1005 1022 1001 1002 1003 1025 1019 1008 1014
 1022 1010 1015 1013 1024 1007 1002 1023]


In [ ]:
result = np.stack((user_id, rider_id), axis=0)

print(result)

[[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
    15   16   17   18   19   20   21   22   23   24   25]
 [1019 1014 1020 1012 1016 1002 1022 1012 1005 1022 1001 1002 1003 1025
  1019 1008 1014 1022 1010 1015 1013 1024 1007 1002 1023]]


[
 [1001 1002 1003 1004 1005]
 [5001 5002 5003 5004 5005]
]

In [ ]:
result = np.stack((user_id, rider_id), axis=1)

print(result)

[[   1 1019]
 [   2 1014]
 [   3 1020]
 [   4 1012]
 [   5 1016]
 [   6 1002]
 [   7 1022]
 [   8 1012]
 [   9 1005]
 [  10 1022]
 [  11 1001]
 [  12 1002]
 [  13 1003]
 [  14 1025]
 [  15 1019]
 [  16 1008]
 [  17 1014]
 [  18 1022]
 [  19 1010]
 [  20 1015]
 [  21 1013]
 [  22 1024]
 [  23 1007]
 [  24 1002]
 [  25 1023]]


In [ ]:
result = np.hstack((user_id, rider_id))

print(result)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25 1019 1014 1020
 1012 1016 1002 1022 1012 1005 1022 1001 1002 1003 1025 1019 1008 1014
 1022 1010 1015 1013 1024 1007 1002 1023]


In [ ]:
result = np.vstack((user_id, rider_id))

print(result)

[[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
    15   16   17   18   19   20   21   22   23   24   25]
 [1019 1014 1020 1012 1016 1002 1022 1012 1005 1022 1001 1002 1003 1025
  1019 1008 1014 1022 1010 1015 1013 1024 1007 1002 1023]]


In [ ]:
result = np.row_stack((user_id, rider_id))

print(result)

[[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
    15   16   17   18   19   20   21   22   23   24   25]
 [1019 1014 1020 1012 1016 1002 1022 1012 1005 1022 1001 1002 1003 1025
  1019 1008 1014 1022 1010 1015 1013 1024 1007 1002 1023]]


/tmp/ipykernel_5692/1428551804.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  result = np.row_stack((user_id, rider_id))


In [ ]:
data = np.column_stack([
    user_id,
    rider_id,
    total_trips,
    distance,
    experience,
    rating
])

print(data)

[[    1  1019   622  2392    12     2]
 [    2  1014   674  1469    15     1]
 [    3  1020   225 10186    14     4]
 [    4  1012   403  2084    16     5]
 [    5  1016   603   686    14     3]
 [    6  1002   198  5232     7     3]
 [    7  1022   415  5994    16     5]
 [    8  1012   516  7055    15     1]
 [    9  1005   176   904     6     1]
 [   10  1022   367   136     8     3]
 [   11  1001   199 10091    13     1]
 [   12  1002   659   821    10     1]
 [   13  1003   369  5228     8     1]
 [   14  1025   206 11234    11     2]
 [   15  1019    40  8696     5     4]
 [   16  1008   316 10908     4     1]
 [   17  1014     0  2861     7     5]
 [   18  1022   618 11448     9     2]
 [   19  1010   586  9200    15     5]
 [   20  1015   486  1963     4     5]
 [   21  1013   161  6053     2     4]
 [   22  1024    91   186     8     4]
 [   23  1007   480  9463    12     5]
 [   24  1002   568  2142    15     3]
 [   25  1023   239  5664    11     5]]


##total rows

In [ ]:
print(data.shape[0])

25


##total features

In [ ]:
print(data.shape[1])

6


In [ ]:
print(data[3][5])

5


In [ ]:
print(data[3:11])

[[    4  1012   403  2084    16     5]
 [    5  1016   603   686    14     3]
 [    6  1002   198  5232     7     3]
 [    7  1022   415  5994    16     5]
 [    8  1012   516  7055    15     1]
 [    9  1005   176   904     6     1]
 [   10  1022   367   136     8     3]
 [   11  1001   199 10091    13     1]]


In [ ]:
print(data[::2])

[[    1  1019   622  2392    12     2]
 [    3  1020   225 10186    14     4]
 [    5  1016   603   686    14     3]
 [    7  1022   415  5994    16     5]
 [    9  1005   176   904     6     1]
 [   11  1001   199 10091    13     1]
 [   13  1003   369  5228     8     1]
 [   15  1019    40  8696     5     4]
 [   17  1014     0  2861     7     5]
 [   19  1010   586  9200    15     5]
 [   21  1013   161  6053     2     4]
 [   23  1007   480  9463    12     5]
 [   25  1023   239  5664    11     5]]


In [ ]:
print(data[1::2])

[[    2  1014   674  1469    15     1]
 [    4  1012   403  2084    16     5]
 [    6  1002   198  5232     7     3]
 [    8  1012   516  7055    15     1]
 [   10  1022   367   136     8     3]
 [   12  1002   659   821    10     1]
 [   14  1025   206 11234    11     2]
 [   16  1008   316 10908     4     1]
 [   18  1022   618 11448     9     2]
 [   20  1015   486  1963     4     5]
 [   22  1024    91   186     8     4]
 [   24  1002   568  2142    15     3]]


In [ ]:
print(data[::,4])

[12 15 14 16 14  7 16 15  6  8 13 10  8 11  5  4  7  9 15  4  2  8 12 15
 11]


In [ ]:
print(data[::,::2])

[[  1 622  12]
 [  2 674  15]
 [  3 225  14]
 [  4 403  16]
 [  5 603  14]
 [  6 198   7]
 [  7 415  16]
 [  8 516  15]
 [  9 176   6]
 [ 10 367   8]
 [ 11 199  13]
 [ 12 659  10]
 [ 13 369   8]
 [ 14 206  11]
 [ 15  40   5]
 [ 16 316   4]
 [ 17   0   7]
 [ 18 618   9]
 [ 19 586  15]
 [ 20 486   4]
 [ 21 161   2]
 [ 22  91   8]
 [ 23 480  12]
 [ 24 568  15]
 [ 25 239  11]]


In [ ]:
print(data[::,1::2])

[[ 1019  2392     2]
 [ 1014  1469     1]
 [ 1020 10186     4]
 [ 1012  2084     5]
 [ 1016   686     3]
 [ 1002  5232     3]
 [ 1022  5994     5]
 [ 1012  7055     1]
 [ 1005   904     1]
 [ 1022   136     3]
 [ 1001 10091     1]
 [ 1002   821     1]
 [ 1003  5228     1]
 [ 1025 11234     2]
 [ 1019  8696     4]
 [ 1008 10908     1]
 [ 1014  2861     5]
 [ 1022 11448     2]
 [ 1010  9200     5]
 [ 1015  1963     5]
 [ 1013  6053     4]
 [ 1024   186     4]
 [ 1007  9463     5]
 [ 1002  2142     3]
 [ 1023  5664     5]]


In [ ]:
experience = data[::,5]
experience[experience>4]

array([5, 5, 5, 5, 5, 5, 5])

In [ ]:
print(data[:,[1,3,4,5]])

[[ 1019  2392    12     2]
 [ 1014  1469    15     1]
 [ 1020 10186    14     4]
 [ 1012  2084    16     5]
 [ 1016   686    14     3]
 [ 1002  5232     7     3]
 [ 1022  5994    16     5]
 [ 1012  7055    15     1]
 [ 1005   904     6     1]
 [ 1022   136     8     3]
 [ 1001 10091    13     1]
 [ 1002   821    10     1]
 [ 1003  5228     8     1]
 [ 1025 11234    11     2]
 [ 1019  8696     5     4]
 [ 1008 10908     4     1]
 [ 1014  2861     7     5]
 [ 1022 11448     9     2]
 [ 1010  9200    15     5]
 [ 1015  1963     4     5]
 [ 1013  6053     2     4]
 [ 1024   186     8     4]
 [ 1007  9463    12     5]
 [ 1002  2142    15     3]
 [ 1023  5664    11     5]]


In [ ]:
data[:,5]

array([2, 1, 4, 5, 3, 3, 5, 1, 1, 3, 1, 1, 1, 2, 4, 1, 5, 2, 5, 5, 4, 4,
       5, 3, 5])

In [ ]:
experience[experience>4]

array([5, 5, 5, 5, 5, 5, 5])