<a href="https://colab.research.google.com/github/prajjaldhar/DataScience/blob/main/WhatsApp_Business_Analytics_NumPy_Only.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📱 WhatsApp Business Analytics:

### problem Statement:
A company uses WhatsApp for customer support and sales. Management wants to understand response speed, resolution efficiency, customer satisfaction, sales value, and agent performance.

**constraint:** NumPy only. No Pandas.

### NumPy concepts covered
- `np.arange`
- `np.random`
- `np.concatenate`
- `np.stack`
- Broadcasting
- Slicing
- Boolean indexing
- Aggregations and basic statistics

All business variables below are numerical.


In [ ]:
import numpy as np
print("NumPy version:", np.__version__)


NumPy version: 2.1.3


## 1. Create the Business Dataset

We will create **20 WhatsApp business chats** and **12 numerical columns**.

| Column | Meaning |
|---|---|
| Chat_ID | Chat identifier |
| Response_Time | Minutes until first response |
| Resolution_Time | Minutes until issue resolution |
| Messages | Messages in conversation |
| Customer_Wait | Minutes customer waited |
| Satisfaction | Rating from 1–5 |
| Order_Value | Order value in ₹ |
| Discount | Discount in ₹ |
| Agent_Efficiency | Efficiency score |
| Followups | Number of follow-ups |
| Escalations | Number of escalations |
| Conversation_Hours | Conversation duration in hours |

We will keep the actual analysis matrix purely numerical.


In [ ]:
# 20 chat IDs
chat_id = np.arange(1, 21)

# Generate numerical business data using np.random
response_time = np.random.randint(2, 31, 20)
resolution_time = np.random.randint(10, 181, 20)
messages = np.random.randint(5, 61, 20)
customer_wait = np.random.randint(1, 46, 20)
satisfaction = np.random.randint(1, 6, 20)
order_value = np.random.randint(500, 10001, 20)
discount = np.random.randint(0, 1501, 20)
agent_efficiency = np.random.randint(60, 101, 20)
followups = np.random.randint(0, 7, 20)
escalations = np.random.randint(0, 4, 20)
conversation_hours = np.random.randint(1, 25, 20)

print("Chat IDs:", chat_id)
print("Response times:", response_time)


Chat IDs: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Response times: [11 22 13 20 13  2  2 15 30  7 13  9  6 13  5  2 11  9 12 18]


## 2. `np.arange` — Create Chat IDs

A business system gives each conversation a sequential ID.

### Practice
- Create IDs from 1 to 20 using `np.arange`.
- Create another array containing 100 to 120.
- Create ids from 150-250
- Create ids from 200-400


In [ ]:
# Student practice
ids_1_to_20 = np.arange(1, 21)
ids_100_to_120 = np.arange(100, 121)

print(ids_1_to_20)
print(ids_100_to_120)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120]


## 3. `np.concatenate` — Combine Data

Imagine the company exported two batches of chats.

**Question:** How can we combine the two batches into one array?


In [ ]:
batch_1 = np.arange(1, 11)
batch_2 = np.arange(11, 21)

all_chats = np.concatenate((batch_1, batch_2))

print("Batch 1:", batch_1)
print("Batch 2:", batch_2)
print("Combined:", all_chats)


Batch 1: [ 1  2  3  4  5  6  7  8  9 10]
Batch 2: [11 12 13 14 15 16 17 18 19 20]
Combined: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## 4. `np.stack` — Build a Business Matrix

Now imagine each metric is one row. We want to place all metrics into a 2D matrix.

### Think:
`concatenate` → join arrays along an existing axis.

`stack` → create a new axis and place arrays together.


In [ ]:
sample_response = response_time[:5]
sample_resolution = resolution_time[:5]
sample_messages = messages[:5]

business_stack = np.stack(
    (sample_response, sample_resolution, sample_messages)
)

print("Stacked shape:", business_stack.shape)
print(business_stack)


Stacked shape: (3, 5)
[[ 11  22  13  20  13]
 [175 103 150  94 126]
 [ 51  28   8  25  36]]


## 5. Build the Complete Numerical Dataset

Each **row = one WhatsApp conversation**.

Each **column = one business metric**.

This is our main NumPy dataset.


In [ ]:
data = np.stack((
    chat_id,
    response_time,
    resolution_time,
    messages,
    customer_wait,
    satisfaction,
    order_value,
    discount,
    agent_efficiency,
    followups,
    escalations,
    conversation_hours
), axis=1)

print("Shape:", data.shape)
# print(*["chat_id",
#     "resp_time",
#     "resolu_time",
#     "msg",
#     "cust_wait",
#     "satftn",
#     "ord_val",
#     "dis",
#     "agnt_eff",
#     "follups",
#     "escltns",
#     "convrsn_hrs"],sep="|")
print(data)


Shape: (20, 12)
[[   1   11  175   51   37    4 8279  983   99    4    3    1]
 [   2   22  103   28   35    3  523  420   65    1    0   21]
 [   3   13  150    8   29    2 6247  497   77    1    1    1]
 [   4   20   94   25   22    1 5946 1119   89    0    0   13]
 [   5   13  126   36    2    2 7790  961   73    1    1   12]
 [   6    2   12   15    7    4 7073   90   85    6    2   19]
 [   7    2   87   32   27    5 4829 1328   78    0    0   18]
 [   8   15   55   37    5    5 4107  252   91    6    1    9]
 [   9   30  154   36   15    4 4290  338   76    5    0    5]
 [  10    7   43   25   40    1 6247  584   60    2    2   11]
 [  11   13  132   36   43    2 7203  297   63    3    2   17]
 [  12    9  172   10   12    2 2937  566   90    5    0    2]
 [  13    6  162   60   34    1 5902  981   61    2    0    8]
 [  14   13  137   26   24    1 3007 1044   92    4    3   23]
 [  15    5  122   13   13    1 2774  668   87    6    3   21]
 [  16    2  178   20   35    5 8883  7

### Column positions

```text
0  Chat_ID
1  Response_Time
2  Resolution_Time
3  Messages
4  Customer_Wait
5  Satisfaction
6  Order_Value
7  Discount
8  Agent_Efficiency
9  Followups
10 Escalations
11 Conversation_Hours
```


#  6. Slicing

Management asks for only the **first 5 conversations**.

Then they ask for:
- response time and resolution time of all chats
- the first 10 chats
- chats 11–15
- order value for the last 5 chats


In [ ]:
first_5 = data[:5]
response_resolution = data[:, 1:3]
first_10 = data[:10]
chats_11_to_15 = data[10:15]
last_5_order_value = data[-5:, 6]

print("First 5:\n", first_5)
print("\nResponse + Resolution:\n", response_resolution)
print("\nFirst 10:\n", first_10)
print("\nChats 11–15:\n", chats_11_to_15)
print("\nLast 5 order values:", last_5_order_value)


First 5:
 [[   1   11  175   51   37    4 8279  983   99    4    3    1]
 [   2   22  103   28   35    3  523  420   65    1    0   21]
 [   3   13  150    8   29    2 6247  497   77    1    1    1]
 [   4   20   94   25   22    1 5946 1119   89    0    0   13]
 [   5   13  126   36    2    2 7790  961   73    1    1   12]]

Response + Resolution:
 [[ 11 175]
 [ 22 103]
 [ 13 150]
 [ 20  94]
 [ 13 126]
 [  2  12]
 [  2  87]
 [ 15  55]
 [ 30 154]
 [  7  43]
 [ 13 132]
 [  9 172]
 [  6 162]
 [ 13 137]
 [  5 122]
 [  2 178]
 [ 11 114]
 [  9  62]
 [ 12  22]
 [ 18 124]]

First 10:
 [[   1   11  175   51   37    4 8279  983   99    4    3    1]
 [   2   22  103   28   35    3  523  420   65    1    0   21]
 [   3   13  150    8   29    2 6247  497   77    1    1    1]
 [   4   20   94   25   22    1 5946 1119   89    0    0   13]
 [   5   13  126   36    2    2 7790  961   73    1    1   12]
 [   6    2   12   15    7    4 7073   90   85    6    2   19]
 [   7    2   87   32   27    5 4829 1

# 7. Boolean Indexing

A manager asks:

> **Which conversations took more than 20 minutes to get a first response?**


In [ ]:
slow_response = data[data[:, 1] > 20]

print("Chats with response time > 20 minutes:")
print(slow_response)


Chats with response time > 20 minutes:
[[   2   22  103   28   35    3  523  420   65    1    0   21]
 [   9   30  154   36   15    4 4290  338   76    5    0    5]]


# 8. Broadcasting

Suppose the company introduces a new service rule:

> **Every conversation gets an automatic 5-minute service buffer added to the recorded customer wait time.**

Use broadcasting to apply the value to the entire array.


In [ ]:
wait_with_buffer = data[:, 4] + 5

print("Original wait:", data[:, 4])
print("After 5-minute buffer:", wait_with_buffer)


Original wait: [37 35 29 22  2  7 27  5 15 40 43 12 34 24 13 35 31 20  4 35]
After 5-minute buffer: [42 40 34 27  7 12 32 10 20 45 48 17 39 29 18 40 36 25  9 40]


## Broadcasting with a Business Matrix

The management team wants to increase every agent's efficiency score by **3 points** for a training simulation.

No loop. No Pandas.


In [ ]:
simulated_efficiency = data[:, 8] + 3

print("Original efficiency:", data[:, 8])
print("Simulated efficiency:", simulated_efficiency)


Original efficiency: [ 99  65  77  89  73  85  78  91  76  60  63  90  61  92  87  96 100  86
  78  98]
Simulated efficiency: [102  68  80  92  76  88  81  94  79  63  66  93  64  95  90  99 103  89
  81 101]


# Final Business Challenge

You are the **Data Analyst for the company's WhatsApp operations team**.

Management asks:

> **"Are our WhatsApp conversations efficient, and where should we improve?"**

Using only NumPy, produce these 5 metrics:

1. Average response time
2. Average resolution time
3. Average satisfaction
4. Total order value
5. Percentage of chats with response time > 20 minutes

Then write **3 business insights** based on the numbers.

### Rule
Don't just give numbers.

Convert:

**Number → Observation → Business Decision**

Example:

> Response time is high → customers wait longer → increase support capacity during peak periods.


In [ ]:
# Final challenge workspace

avg_response = np.mean(data[:, 1])
avg_resolution = np.mean(data[:, 2])
avg_satisfaction = np.mean(data[:, 5])
total_order_value = np.sum(data[:, 6])

slow_percentage = np.mean(data[:, 1] > 20) * 100

print("Average response time:", avg_response)
print("Average resolution time:", avg_resolution)
print("Average satisfaction:", avg_satisfaction)
print("Total order value: ₹", total_order_value)
print("Chats with response > 20 min:", slow_percentage, "%")


Average response time: 11.65
Average resolution time: 111.2
Average satisfaction: 3.0
Total order value: ₹ 110436
Chats with response > 20 min: 10.0 %


#  9. Business Questions
— Solve These

Use **only NumPy**. Do not use Pandas, loops, or other data-analysis libraries.

### Basic
1. How many total WhatsApp conversations are present?
2. What is the average response time?
3. What is the fastest response time?
4. What is the slowest response time?
5. What is the average resolution time?
6. What is the average customer satisfaction score?

### Business Analysis
7. Which conversations have a satisfaction score below 3?
8. Which conversations took more than 120 minutes to resolve?
9. Which conversations generated an order value greater than ₹7,000?
10. How many conversations required at least 2 escalations?
11. What is the total order value generated?
12. What is the average order value?
13. Which 5 conversations have the highest order values? *(Hint: `np.sort` / indexing)*
14. What is the standard deviation of response time?
15. What is the standard deviation of order value?
16. Find conversations where response time is above 20 minutes **AND** satisfaction is below 3.
17. Find conversations where messages are above 40 **OR** escalations are at least 2.
18. Calculate the average response time only for conversations with satisfaction ≥ 4.
19. Calculate the total order value only for conversations resolved in less than 60 minutes.
20. If the company wants to reduce every response time by 2 minutes in a simulation, create the new response-time array using broadcasting.
21. What is the highest satisfaction score given by customers?
22. What is the lowest satisfaction score given by customers?
23. How many conversations have a satisfaction score of 5?
24. How many conversations have a satisfaction score of 1?
25. What is the total number of messages across all conversations?
26. What is the average number of messages per conversation?
27. What is the highest number of messages in any conversation?
28. What is the lowest number of messages in any conversation?
29. What is the total number of follow-ups across all conversations?
30. What is the average number of follow-ups per conversation?
31. Create a new array containing only the response times greater than 15 minutes.
32. Create a new array containing only the order values greater than ₹7,000.
33. Create a new array containing only the satisfaction scores of 4 or 5.
34. Create a new array containing only the resolution times below 60 minutes.
35. Add 5 minutes to every response time using broadcasting.
36. Subtract 10 minutes from every resolution time using broadcasting.
37. Increase every order value by ₹500 using broadcasting.
38. Reduce every order value by ₹1,000 using broadcasting.
39. Create an array containing the difference between resolution time and response time for every conversation.
40. Create an array containing the total customer interaction by adding messages + followups.
